### ISSUE TITLE
No Support for SASS/SCSS OOTB?

### ISSUE THREAD

**Issue by boxdox** [fspoettel/blaupause#230]
Why isn't there support for SASS/SCSS out of the box? Shouldn't that help make css more readable?

**Comment by fspoettel** [comment]
Hey!

> Why isn't there support for SASS/SCSS out of the box? 

Mostly personal preference. The things I use this boilerplate for usually are not complex / big enough to warrant using scss out of the box. I can see that it is sth. that many people expect from a boilerplate though.

> Shouldn't that help make css more readable?

In theory yes. Working on larger projects with a lot of contributors I found that this is not necessarily the case all the time. Especially SASS' nesting support is sth. that can lead to a lot less readable code when not careful.

**Comment by boxdox** [comment]
> Mostly personal preference

Okay, I want to integrate SCSS into my workflow, i will be installing node-sass as dependency and adding task after https://github.com/fspoettel/blaupause/blob/9f8fe83ac1f43ef112217b6eeb62d1bf0da6be45/package-scripts.js#L30 ?

**Comment by fspoettel** [comment]
In theory, it should be sufficient to pipe `node-sass` into `postcss` like `node-sass index.scss | postcss ....` and adjust the watched files. I have not tried this yet though. Let me know if that works and I will add it to the README
